// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QRefeicao.Data;

#nullable disable

namespace QRefeicao.Data.Migrations
{
    [DbContext(typeof(QRContext))]
    [Migration("20250610185755_RestauranteUpdates")]
    partial class RestauranteUpdates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QRefeicao.Data.Models.AssinaturaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataFim");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInclusao");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInicio");

                    b.Property<Guid>("IdTGStatusAssinatura")
                        .HasColumnType("uuid")
                        .HasColumnName("IdTGStatusAssinatura");

                    b.Property<Guid>("IdTGTipoAssinatura")
                        .HasColumnType("uuid")
                        .HasColumnName("IdTGTipoAssinatura");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("IdTGStatusAssinatura");

                    b.HasIndex("IdTGTipoAssinatura");

                    b.ToTable("Assinatura");
                });

            modelBuilder.Entity("QRefeicao.Data.Models.CardapioItemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("CardapioId")
                        .HasColumnType("uuid")
                        .HasColumnName("CardapioId");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("CategoriaId");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInclusao");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("Descricao");

                    b.Property<byte[]>("ImagemBytes")
                        .HasColumnType("bytea")
                        .HasColumnName("ImagemBytes");

                    b.Property<string>("ImagemURL")
                        .HasColumnType("text")
                        .HasColumnName("ImagemURL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("Ordem");

                    b.Property<decimal>("Preco")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("Preco");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("CardapioId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("CardapioItem");
                });

            modelBuilder.Entity("QRefeicao.Data.Models.CardapioModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInclusao");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("Descrição");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("uuid")
                        .HasColumnName("RestauranteId");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Cardapio");
                });

            modelBuilder.Entity("QRefeicao.Data.Models.CategoriaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("Ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInclusao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.Property<int>("OrdemExibicao")
                        .HasColumnType("integer")
                        .HasColumnName("OrdemExibicao");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("uuid")
                        .HasColumnName("RestauranteId");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("QRefeicao.Data.Models.RestauranteIdiomaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInclusao");

                    b.Property<Guid>("IdTGIdioma")
                        .HasColumnType("uuid")
                        .HasColumnName("IdTGIdioma");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("uuid")
                        .HasColumnName("RestauranteId");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("IdTGIdioma");

                    b.HasIndex("RestauranteId");

                    b.ToTable("RestauranteIdioma");
                });

            modelBuilder.Entity("QRefeicao.Data.Models.RestauranteModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("CorPrincipal")
                        .HasColumnType("text")
                        .HasColumnName("CorPrincipal");

                    b.Property<string>("CorSecundaria")
                        .HasColumnType("text")
                        .HasColumnName("CorSecundaria");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInclusao");

                    b.Property<byte[]>("LogoBytes")
                        .HasColumnType("bytea")
                        .HasColumnName("LogoBytes");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("UsuarioAlteracao");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("UsuarioId");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UsuarioInclusao");

                    b.HasKey("Id");

                    b.ToTable("Restaurante");
                });

            modelBuilder.Entity("QRefeicao.Data.Models.TabelaGeralItemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInclusao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Descricao");

                    b.Property<Guid?>("RestauranteModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("Sigla");

                    b.Property<Guid>("TabelaGeralId")
                        .HasColumnType("uuid")
                        .HasColumnName("TabelaGeralId");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteModelId");

                    b.HasIndex("TabelaGeralId");

                    b.ToTable("TabelaGeralItem");
                });

            modelBuilder.Entity("QRefeicao.Data.Models.TabelaGeralModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInclusao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UsuarioInclusao");

                    b.HasKey("Id");

                    b.ToTable("TabelaGeral");
                });

            modelBuilder.Entity("QRefeicao.Data.Models.AssinaturaModel", b =>
                {
                    b.HasOne("QRefeicao.Data.Models.TabelaGeralItemModel", "StatusAssinatura")
                        .WithMany()
                        .HasForeignKey("IdTGStatusAssinatura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRefeicao.Data.Models.TabelaGeralItemModel", "TipoAssinatura")
                        .WithMany()
                        .HasForeignKey("IdTGTipoAssinatura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusAssinatura");

                    b.Navigation("TipoAssinatura");
                });

            modelBuilder.Entity("QRefeicao.Data.Models.CardapioItemModel", b =>
                {
                    b.HasOne("QRefeicao.Data.Models.CardapioModel", "Cardapio")
                        .WithMany("ItensCardapio")
                        .HasForeignKey("CardapioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRefeicao.Data.Models.CategoriaModel", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cardapio");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("QRefeicao.Data.Models.CardapioModel", b =>
                {
                    b.HasOne("QRefeicao.Data.Models.RestauranteModel", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("QRefeicao.Data.Models.CategoriaModel", b =>
                {
                    b.HasOne("QRefeicao.Data.Models.RestauranteModel", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("QRefeicao.Data.Models.RestauranteIdiomaModel", b =>
                {
                    b.HasOne("QRefeicao.Data.Models.TabelaGeralItemModel", "Idioma")
                        .WithMany()
                        .HasForeignKey("IdTGIdioma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRefeicao.Data.Models.RestauranteModel", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idioma");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("QRefeicao.Data.Models.TabelaGeralItemModel", b =>
                {
                    b.HasOne("QRefeicao.Data.Models.RestauranteModel", null)
                        .WithMany("Idiomas")
                        .HasForeignKey("RestauranteModelId");

                    b.HasOne("QRefeicao.Data.Models.TabelaGeralModel", "TabelaGeral")
                        .WithMany()
                        .HasForeignKey("TabelaGeralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TabelaGeral");
                });

            modelBuilder.Entity("QRefeicao.Data.Models.CardapioModel", b =>
                {
                    b.Navigation("ItensCardapio");
                });

            modelBuilder.Entity("QRefeicao.Data.Models.RestauranteModel", b =>
                {
                    b.Navigation("Idiomas");
                });
#pragma warning restore 612, 618
        }
    }
}
